<a href="https://colab.research.google.com/github/Hariom-Patel123/NUMPYLIBRARY/blob/main/nump1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([4,8,12,16,20])
print(a)

[ 4  8 12 16 20]


In [3]:
b=np.array([4,8,12,16,20])
print(a+b)

[ 8 16 24 32 40]


In [4]:
b+2

array([ 6, 10, 14, 18, 22])

In [5]:
b**2

array([ 16,  64, 144, 256, 400])

In [ ]:
##GIVEN A LIST OF THE PRIXCES
prices=