<a href="https://colab.research.google.com/github/Hariom-Patel123/NUMPYLIBRARY/blob/main/nump2_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr=np.array([2,4,6,8,10])
print(arr)
result=arr*1
print(result)
result=arr*2
print(result)
result=arr*3
print(result)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 4  8 12 16 20]
[ 6 12 18 24 30]


In [7]:
a=np.array([1,2,3])
b=np.array([1.5,2.5,3.5])
print(a.dtype)
print(b.dtype)
c=a+b
print(c)
print(type(c))

int64
float64
[2.5 4.5 6.5]
<class 'numpy.ndarray'>


In [15]:
a=np.array([
    [10,20,30],
    [40,50,60]
])
print(a[(0,0)])
print(a[0])
print(a.shape)
print(a.ndim)
print(a.size)


10
[10 20 30]
(2, 3)
2
6


In [18]:
b=np.ones(5)
print(b)

[1. 1. 1. 1. 1.]
