<a href="https://colab.research.google.com/github/Hariom-Patel123/NUMPYLIBRARY/blob/main/nump3_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
marks=np.array([70,99,98,68,86])
b=np.array(marks)
print(b.dtype)

int64


In [ ]:
print(marks.size)

5


In [ ]:
print(marks.ndim)

1


In [ ]:
n=len(marks)
for i in range(n):
  print(marks[i])

70
99
98
68
86


In [ ]:
print(marks.shape)

(3,)


In [ ]:
print(marks[-1])

86


In [ ]:
marks=np.array([
    [70,80,90],
    [60,70,80],
    [49,79,89]
])
print(marks)
print(marks[0,2])

[[70 80 90]
 [60 70 80]
 [49 79 89]]
90


In [ ]:
###A COLLEGE STORES MARKS OF 4 STUDENTS  IN 3 SUBJECTS: MATH, SCIENCE, ENGLISH
marks=np.array([
    [70,88,99],
    [87,95,89],
    [82,90,89]
])
print(marks)
### DISPLAY MARKS OF 3RD STUDENT
print("marks of the 1st student: ",marks[0])
### DISPLAY MARKS OF SCIENCE SUBJECT MARKS OF 2ND STUDENT
print("marks of he science: ",marks[1,1])
### DISPLAY MARKS OF SCIENCE SUBJECT MARKS OF ALL
print("marks of science: ",marks[:,1])
### ADD 5 MARKS TO EVERY SCIENCE STUDENT
marks[:,1]=marks[:,1]+5
print(marks)
### Change the math's marks of 1srt students to 75
marks[0,0]=75
print(marks)



[[70 88 99]
 [87 95 89]
 [82 90 89]]
marks of the 1st student:  [70 88 99]
marks of he science:  95
marks of science:  [88 95 90]
[[ 70  93  99]
 [ 87 100  89]
 [ 82  95  89]]
[[ 75  93  99]
 [ 87 100  89]
 [ 82  95  89]]


In [ ]:
###A COMPANY RECORDS 3 MONTS SALES [(JAN FEB MARCH):columns]
sales=np.array([
    [120,240,360],
    [110,220,330],
    [100,200,300]
])
##display the sales of branch 2
print(sales[1])

[110 220 330]


In [ ]:
##DISPLAY THE SALES OF FEBRUARY
print(sales[:,1])

[240 220 200]


In [ ]:
####INCREASE THE MARCH SALES BY 10 PERCENT
incrementd=sales[:,2]+0.1*sales[:,2]
print(incrementd)

[396. 363. 330.]


In [ ]:
#### AN ORGANIZATION STORES EMPLOYEE SALARY | EXPERIANCE
salary=np.array([
    [30000,3],
    [40000,4],
    [50000,5]
]

)
###DISPLAY THE SALARY AQND EXPERIANCE OF LAST CANDIATE(USE BEGATIVE INDEXING)
print(salary[-1])

[50000     5]


In [ ]:
#### DISPLAY THE SALARY OF 2ND EMPLOYEE
print(salary[1,0])

40000


In [ ]:
#### INCREASE THE SALARY OF 3RD EMPLOYEE BY  15 PERCENT
a=salary[2,0]
a=a+a*0.15
print(a)

57500.0


In [ ]:
###ADD 1 YEAR EXPERIANCE TO THE 1STR EMPLOYEE
salary[0,1]=salary[0,1]+1
print(salary)

[[30000     4]
 [40000     4]
 [50000     5]]


In [ ]:
####A COMPANY HAS INVENTORY INFORMATIONS FOR THE 4 PRODUCTS ACROSS 4 WAREHOUSES
### columns : WAREHOUSE A ,WAREHOUSE B, WAREHOUSE C,WAREHOUSE D
inventory=np.array([
    [100,20,39,28],
    [200,30,40,22],
    [300,40,50,89],
    [400,50,60,99]
])
#####DISPLAY INVENTORY OF PRODUCT 3 ACROSS ALL WAREHOUSES
print(inventory[:,2])


[39 40 50 60]


In [ ]:
### DISPLAY THE INVENTORY OF WAREHOUSE B
print(inventory[:,1])

[20 30 40 50]


In [ ]:
####WAREHOUSE A RECIEVES 20 EXTRA PRODUCTS UPDATE THE ARRAY
inventory[:,0]=inventory[:,0]+20
print(inventory)

[[120  20  39  28]
 [220  30  40  22]
 [320  40  50  89]
 [420  50  60  99]]


In [ ]:
inventory[3,2]=100
print(inventory)

[[120  20  39  28]
 [220  30  40  22]
 [320  40  50  89]
 [420  50 100  99]]


In [51]:
### A WEATHER APPLCATION STORES TEMPERATURE OF 3 CITIES
### COLUMNS :MORNING AFTERNOON EVENING
temperature=np.array([
    [24,35,28],
    [22,32,26],
    [27,38,30]
])
###DISPLAY THE COMPLETE DATA TEMPERATURE OF CITY 1
print(temperature[0])

[24 35 28]


In [52]:
####DISPLAY ALL AFTERNOON TEMPERATURES
print(temperature[:,1])

[35 32 38]


In [55]:
#####DISPLAY THE EVENING TEMPERATURE OF THE LAST CITY USING NEGATIVE INDEXING
print(temperature[-1,2])

38


In [57]:
####INCRESE ALL MORNING TEMPERATURES BY 2 DEGREE CENTIGRADE
temperature[:,0]=temperature[:,0]+2
print(temperature)

[[28 35 28]
 [26 32 26]
 [31 38 30]]
