<a href="https://colab.research.google.com/github/Hariom-Patel123/NUMPYLIBRARY/blob/main/nump2_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([2,4,6,8,10])
print(arr)
result=arr*1
print(result)
result=arr*2
print(result)
result=arr*3
print(result)

[ 2  4  6  8 10]
[ 2  4  6  8 10]
[ 4  8 12 16 20]
[ 6 12 18 24 30]


In [ ]:
a=np.array([1,2,3])
b=np.array([1.5,2.5,3.5])
print(a.dtype)
print(b.dtype)
c=a+b
print(c)
print(type(c))

int64
float64
[2.5 4.5 6.5]
<class 'numpy.ndarray'>


In [ ]:
a=np.array([
    [10,20,30],
    [40,50,60]
])
print(a[(0,0)])
print(a[0])
print(a.shape)
print(a.ndim)
print(a.size)


10
[10 20 30]
(2, 3)
2
6


In [19]:
b=np.ones(5)
print(b)

[1. 1. 1. 1. 1.]


In [20]:
c=np.zeros(8)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
arr=np.full(5,2)
print(arr)

[2 2 2 2 2]


In [26]:
arr=np.zeros((3,4))
print(arr)
print(arr+10)
print(arr*10)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
###CHALLENGE QUESTION
arr=np.ones((4,4))
print(arr)
result=arr*10
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [31]:
arr=np.full(4,50)
print(arr)

[50 50 50 50]


In [33]:
##GOOD QUESTION
celsius=np.array([0,10,20,30,40,50])
f=celsius*9/5+32
print(celsius)
print(f)

[ 0 10 20 30 40 50]
[ 32.  50.  68.  86. 104. 122.]


In [34]:
###CASESTUDY
### A STUDENT SCORED MARKS
marks=np.array([67,70,80,90,94])
bonus=5
print(marks+bonus)

[72 75 85 95 99]


In [35]:
###CASESTUDY
### A SHOP HAVE 5 PRODUCTS
###100 200 300 400 500
##CALCULATE PRICE AFTER APPLYING 10 PERCENT DISCOUNT
prices=np.array([100,200,300,400,500])
after=[]
price_after_discount=prices-0.1*prices
print(price_after_discount)

[ 90. 180. 270. 360. 450.]


In [37]:
##A COMPANY HAVE 5 EMPLOYEES
##10000 20000 3000000 4000000 500000
##CREATE ARRAYS OF SALARY AND GIVE 10 PERCENT INCREMENT
salary=np.array([10000,20000,3000000,4000000,500000
])
incremented_salary=salary*10+salary
print(incremented_salary)

[  110000   220000 33000000 44000000  5500000]


In [38]:
###convert tuples of elemnts into numpy array
a=(2,4,6,8,10)
b=np.array(a)
print(b)


[ 2  4  6  8 10]


In [41]:
##A COMPANY RECORDS SALES FOR 4 QUARTERS
##Q1 =125000
##Q2 =135000
##Q3 =145000
quarters=np.array([125000,135000,145000])
print(quarters)
###add 15percent higher
higher_sales=quarters+quarters*0.15
print(higher_sales)
#

[125000 135000 145000]
[143750. 155250. 166750.]


In [45]:
BRANCH_A=[120,202,384,737,367]
BRANCH_B=[120,2024,484,747,767]
Branch_A=np.array(BRANCH_A)
Branch_B=np.array(BRANCH_B)
print("TOTAL INVENTORY: ",Branch_A+Branch_B)
print("DIFFERENCE: ",Branch_A-Branch_B)


TOTAL INVENTORY:  [ 240 2226  868 1484 1134]
DIFFERENCE:  [    0 -1822  -100   -10  -400]
