<a href="https://colab.research.google.com/github/Hariom-Patel123/NUMPYLIBRARY/blob/main/nump1_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([4,8,12,16,20])
print(a)

[ 4  8 12 16 20]


In [3]:
b=np.array([4,8,12,16,20])
print(a+b)

[ 8 16 24 32 40]


In [4]:
b+2

array([ 6, 10, 14, 18, 22])

In [5]:
b**2

array([ 16,  64, 144, 256, 400])

In [6]:
##GIVEN A LIST OF THE PRIXCES
prices=[50,27,27372]
GST_PRICE=[]
for p in prices:
  GST_PRICE.append(p+0.18*p)
print(GST_PRICE)


[59.0, 31.86, 32298.96]


In [11]:
v=np.linspace(0,10,5)
print(v)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
num=(4,6,3,1)
a=np.array(num)
print(a)

[4 6 3 1]


In [14]:
type(a)

numpy.ndarray

In [16]:
marks=np.array([
    [70,80,90],
    [60,80,100]
])
print(marks[0,1])

80


In [17]:
np.full(6,2)

array([2, 2, 2, 2, 2, 2])

In [18]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])